# Server Configuration
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/books_testing
spring.datasource.username=postgres
spring.datasource.password=postgres