# App name
spring.application.name=book-app

# Connection Validation (mandatory for production reliability)
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Active profile
spring.profiles.active=local